apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "metricbeat-*"
    jsonData:
      index: "metricbeat-*"
      timeField: "@timestamp"
      esVersion: "8.0.0"
